### ISSUE TITLE
Added computation method of the inertia matrix of a kinematic chain. 

### ISSUE THREAD

**Issue by zhidao** [mi-lib/roki#10]
@categoryik Please see rkChainInertiaMatrix() in src/rk_chain.c.
I merged computations of the inertia matrix and the bias force vector into one function since they are often required at the same time.
You can also find an example (benchmark test) code, which I made based on your calc_dynamics_eq_items.c. Check it out for your reference.
Please close this issue if you are convinced with the revisions.

**Comment by categoryik** [comment]
Thank you for informing me.
I felt the name `rkChainInertiaMatrix()` may lead misunderstand for users, because this method name not seems to calculate bias forces. For alternative, how is `rkChainInertiaMatrixAndBias()`? 
The term `And` may be not your favor.

**Comment by zhidao** [comment]
Makes sense. What do you think about `rkChainInertiaMatBiasVec()` ?

**Comment by categoryik** [comment]
@zhidao I agree with your opinion.

**Comment by zhidao** [comment]
Done.
