### ISSUE TITLE
API (and some hidden functions) in rk_abi

### ISSUE THREAD

**Issue by zhidao** [mi-lib/roki#14]
@n-wakisaka rk_abiの関数について質問＆相談です。
一つ目、GetWrenchを含む関数
rkLinkABIUpdateForwardGetWrench()
rkChainABIUpdateGetWrench()
rkChainABIUpdateAddExForceGetWrench()
について、
 - 関数名に動詞が2個以上入っているのが気になります。GetWrenchを単にWrenchとすると意味合いが変わってしまうでしょうか？
 - GetWrenchするものとしないものではどう違いがあるのでしょうか？BrFloat関数で破断を表すのに使っているように見えますが、GetWrenchが付いていない版は計算の過程で関節原点にかかる6軸力を求めないということでしょうか？これを無くすと問題があるでしょうか？

二つ目、ExForceを含む関数
_rkLinkABIFindBackwardPathAddExForce()
_rkLinkABISubBiasNetWrenchAddExForce()
_rkLinkABIUpdateBackwardAddExForce()
_rkChainABIUpdateBackwardAddExForce()
rkChainABIUpdateAddExForce()
rkChainABIUpdateAddExForceGetWrench()
rkChainABIPopPrAccBiasAddExForceTwo()
_rkLinkABIFindBackwardPathAddExForceOne()
_rkLinkABIFindBackwardPathAddExForceTwo()
rkChainABIUpdateAddExForceTwo()
について、
 - rkBody, rkLink, rkChainではExtForceと言っていますが、同じものでしょうか？統一しても問題ないですか？
 - これも関数名に動詞が2個以上入っているのが気になります。関数は一つの動作をする→一つの動詞で説明できるべき、というのが僕の考えです。実際それぞれの関数の中身を見ると、二つも三つも何かをやっているようには見えません。それぞれ何をする関数、と簡潔に説明できるでしょうか？
 - そもそもAddExForceとはどういう操作を指しているのでしょうか？
 - 後ろの方にあるOneとかTwoはどういう意味ですか？

**Comment by n-wakisaka** [comment]
### 1つめ
> 関数名に動詞が2個以上入っているのが気になります。GetWrenchを単にWrenchとすると意味合いが変わってしまうでしょうか？

仰られているとおり，GetWrenchがついている方は関数は関節原点にかかる6軸力を求めるもので，Wrenchでも大丈夫だと思います．

> GetWrenchするものとしないものではどう違いがあるのでしょうか？BrFloat関数で破断を表すのに使っているように見えますが、GetWrenchが付いていない版は計算の過程で関節原点にかかる6軸力を求めないということでしょうか？これを無くすと問題があるでしょうか？

RoKiの中ではBrFloatにしか使っていないですが，RoKiFDの中でどちらも使っています．

#### 補足
関節原点にかかる6軸力自体は計算に使っていないのでアウトプットのためだけに計算しているのですが，積分にルンゲクッタ法を使っているので4回計算する内の最後の1回だけ計算すればよいという形になります．そのため計算するしない2つ関数を用意しています．
関数を2つ用意せず引数で制御しても良かったのですが，比較が増えるのが嫌でこのようにしています．

### 関数名に関して
直接の質問内容ではないのですが，関数名に関しては，rkChainABIUpdateは，たとえば，rkChainFKに対するrkChainUpdateFKと意図は同じなので，rkChainUpdateABIの方がいいかもしれません．
当時おそらく，rkChainABIUpdate までをクラス名のような気持ちで関数名をつけていってしまって，Updateに動詞的な意味をあまり考えていなかった気がします．

ですので，同様にrkChainABIUpdateInit はrkChainInitABIで良い気がします．
rkChainABIUpdateForwardはいわゆるABI法のforward pathの計算で，あまり変わらないかもしれませんが，rkChainCalcABIForwardPathとかでもいいかもしれません．

### 2つめ
#### 2-1
> rkBody, rkLink, rkChainではExtForceと言っていますが、同じものでしょうか？統一しても問題ないですか？

ABI内ではExtWrenchを外力という意味で使っています．Link, ChainなどがExtForceにリネームされるなら同じくリネームして大丈夫です．

#### 2-2
> これも関数名に動詞が2個以上入っているのが気になります。関数は一つの動作をする→一つの動詞で説明できるべき、というのが僕の考えです。実際それぞれの関数の中身を見ると、二つも三つも何かをやっているようには見えません。それぞれ何をする関数、と簡潔に説明できるでしょうか？
> そもそもAddExForceとはどういう操作を指しているのでしょうか？

これらの関数はRoKiFDでの使い方に特化した枝刈り版ABI法の関数群になっています．
ABI法のbackward pathは一般化座標が同じなら，外力が加わっているリンクとその親リンク以外は外力がない場合の計算のキャッシュが効くことを利用したものになります．
ですので，AddExForceは"位置・姿勢の変化がなく外力だけ変わった版"ABI法という意図がありました．
リネームするなら，あまりぱっと名前が思いつかないのですが，CachedABIとかFDでしかつかわないのでrkFDChainABIとかになるでしょうか．

> _rkLinkABIFindBackwardPathAddExForce()

外力が加わっているか確認し，backward pathの計算が必要なリンクにフラグを立てていく関数です．

> _rkLinkABISubBiasNetWrenchAddExForce()

外力の和からABBiasを更新する関数です．

> _rkLinkABIUpdateBackwardAddExForce()

backword pathの計算が必要なリンクをたどり，ABIを更新する関数です．

> _rkChainABIUpdateBackwardAddExForce()

上の関数の再帰処理の起点になる関数です．

> rkChainABIUpdateAddExForce()

外力がない場合の計算のキャッシュを使う版rkChainABIUpdate関数です．

> rkChainABIUpdateAddExForceGetWrench()

上の関数の関節に加わる6軸力をアウトプットとして計算する版の関数です．

#### 2-3
> 後ろの方にあるOneとかTwoはどういう意味ですか？

RoKiFDでのABIの使い方ですが，逆慣性行列を計算するためにいわゆる単位ベクトル法のように外力の要素のうち1つが1.0にしてすべての要素についてそれぞれABI法を適用します．
そのため，外界との接触点の場合1つ，自己干渉の場合2つしか外力が加わる点がないことが分かっているため，それぞれについてさらに計算を簡略化した版がOne, Twoと名前が付いた関数になります．

> rkChainABIPopPrpAccBiasAddExForceTwo()

外力が1,2つだった場合のABI計算後，外力がない場合の計算結果に復元する関数です．

> _rkLinkABIFindBackwardPathAddExForceOne()

_rkLinkABIFindBackwardPathAddExForceの外力が1つだけ版の関数です．
外力が加わっているリンクの親側にたどってフラグを立てるだけの関数になります．

> _rkLinkABIFindBackwardPathAddExForceTwo()

上の関数の外力が2つの場合の関数です．

> rkChainABIUpdateAddExForceTwo()

rkChainABIUpdateAddExForce関数の外力が2つだけ版の関数です．

### その他
全体的にFDに特化した関数が多いため，分離してrkfd_abiとしてRoKiFDにいれてもいいかもと思いました．
いずれにせよ関数名は考える必要はありますが...

p.s. 計算方法について以前まとめたドキュメントがあるのでメールで送付しておきます．

**Comment by n-wakisaka** [comment]
すいません，2つめの解答中に思い出したのですが，1つめの補足について
> 関節原点にかかる6軸力自体は計算に使っていないのでアウトプットのためだけに計算しているのですが，積分にルンゲクッタ法を使っているので4回計算する内の最後の1回だけ計算すればよいという形になります．そのため計算するしない2つ関数を用意しています．

というより，接触力計算で逆慣性行列の計算のために接触点数x3回ABI法を呼ぶので，毎回使わない関節原点にかかる6軸力の計算をスキップするだけで計算量をがっつり削減できそうだったというのが大きかった記憶があります．

**Comment by zhidao** [comment]
回答どうもありがとう。

### 1. rk_abi内関数名について
戴いた説明を元に、各関数を次のように名前変えるのが良いかと思いました。
```
_rkLinkABIInitInertia -> _rkLinkInitABIInertia
rkLinkABIAlloc -> rkLinkAllocABI
rkChainABIAlloc -> rkChainAllocABI
rkLinkABIDestroy -> rkLinkDestroyABI
rkChainABIDestroy -> rkChainDestroyABI
rkLinkABIUpdateInit -> rkLinkInitABI
rkChainABIUpdateInit -> rkChainInitABI
_rkLinkABIAddBias -> _rkLinkUpdateABIBias
_rkLinkABIUpdateBackward -> _rkLinkUpdateABIBackward
rkLinkABIUpdateBackward -> rkLinkUpdateABIBackward
_rkLinkABIUpdateForward -> _rkLinkUpdateABIForward
rkLinkABIUpdateForward -> rkLinkUpdateABIForward
rkLinkABIUpdateForwardGetWrench -> rkLinkUpdateABIWrenchForward
rkChainABIUpdate -> rkChainUpdateABI
rkChainABIUpdateGetWrench -> rkChainUpdateABIWrench
rkChainABI -> rkChainFD_ABI
_rkLinkABIFindBackwardPathAddExForce -> _rkLinkCheckABIExtWrench
_rkLinkABISubBiasNetWrenchAddExForce -> _rkLinkSubABIExtWrench
_rkLinkABIUpdateBackwardAddExForce -> _rkLinkUpdateCachedABIBackward
_rkChainABIUpdateBackwardAddExForce -> _rkChainUpdateCachedABIBackward
rkChainABIUpdateAddExForce -> rkChainUpdateCachedABI
rkChainABIUpdateAddExForceGetWrench -> rkChainUpdateCachedABIWrench
rkChainABIPushPrpAccBias -> rkChainSaveABIAccBias
rkChainABIPopPrpAccBias -> rkChainRestoreABIAccBias
rkChainABIPopPrpAccBiasAddExForceTwo -> rkChainRestoreABIAccBiasPair
_rkLinkABIFindBackwardPathAddExForceOne -> _rkLinkCheckABIExtWrenchSole
_rkChainABIUpdateBackwardAddExForceTwo -> _rkChainCheckABIExtWrenchPair
rkChainABIUpdateAddExForceTwo -> _rkChainUpdateCachedABIPair
```
どうでしょうか？

### 2. 順動力学関数のAPIについて
最近、RoKiでリンク系運動方程式の慣性行列＆バイアス力ベクトル計算をライブラリに入れました。rkChainInertiaMat, rkChainBiasVecです。これを使ってrkChainFDという関数を作ろうかなと思っています。上で、脇坂くんが作ってくれたrkChainABIをrkChainFD_ABIに変えるという提案は、これとコンパチにする意図があります。

それで気付いたのですが、逆動力学の方は
```
void rkChainID(rkChain *c, zVec vel, zVec acc);
```
としているので、順動力学の方は
```
void rkChainFD(rkChain *c, zVec vel, zVec trq);
```
とすべきじゃないのかな、と今更思いました。

ただしご存じの通り、rkChainへの入力は関節トルクなのか？モータ指令なのか？という問題もあります。
rkChainID()は計算後にrkChainGetJointTrqAll()などで関節トルクをとってくることを前提にしている（新しく作ったrkChainInertiaMat()などはそうしてます）のですが、運動からモータ指令を逆算する関数も要るのじゃないか？などとも考えてます。

これについても意見もらえたら有難いです。

**Comment by n-wakisaka** [comment]
### 1
関数の名前変更問題ないと思います．

> rkChainABIをrkChainFD_ABIに変えるという提案は、これとコンパチにする意図があります。

理解しました．

### 2
今ABI法は入力はモータ指令のみになっており，関節トルクを入れたい場合はモータをrkMotorTrqにしてトルクをモータ指令としてあたえるようになっています．
DCモータモデルで直接トルクを与えれるように改良することは可能だと思いますが，変数を見てどちらを採用するか判断させるより別の関数にしてしまったほうがいい感じがしました．
ですので，

> としているので、順動力学の方は
void rkChainFD(rkChain *c, zVec vel, zVec trq);
とすべきじゃないのかな、と今更思いました。

こちらに関して，引数は良いと思いましたが，直接トルクを与える関数とモータ指令を与える関数でわけるといいのかな？と思いました．


> ただしご存じの通り、rkChainへの入力は関節トルクなのか？モータ指令なのか？という問題もあります。
rkChainID()は計算後にrkChainGetJointTrqAll()などで関節トルクをとってくることを前提にしている（新しく作ったrkChainInertiaMat()などはそうしてます）のですが、運動からモータ指令を逆算する関数も要るのじゃないか？などとも考えてます。

両方あっていいと思いました．
今実装しているDCモータモデルだと駆動トルク，関節速度，関節加速度からモータ指令が一意に決まるので，その計算をする関数を用意して，rkChainIDの後に入れるだけで実装はできそうです．

**Comment by zhidao** [comment]
rk_abiの関数群リネームは上記の通り完了しました。RoKi-FDへの反映お願いします。 @n-wakisaka 
順動力学の入力を関節トルク／モータ指令電圧にとる関数の実装は先送りしてます。
