### ISSUE TITLE
Abolish _util member of rkLink?

### ISSUE THREAD

**Issue by zhidao** [mi-lib/roki#18]
rkLink has a _util member, which is a void pointer and is originally intended to be available for programmers' utility purposes.
We have been using RoKi for many years but never seen any cases where _util is utilized :p
What do you think if we abolish it? @n-wakisaka

**Comment by n-wakisaka** [comment]
日本語ですいません．
昔はrkABIPrpを入れるのに使っていたりしましたが，いまは使っていないのでなくしてもいいと思います．

少なくともRoKi内で使うことはなさそうに思います．RoKi内で_utilを使う場合，rkABIPrpのようにいずれちゃんとした名前をつけてrkLinkのメンバに入ると思いました．
ですので，ユーザが使う想定になりますが，無くてもrkLinkに付随した情報を管理する方法はあるので，ぱっとみ使いみちがわからない_utilは無くてもよいかなと思いました．

逆に，rkChain, rkLink, rkBody, rkJointなど主要なクラス全てに追加情報をいれておける辞書(key:str, value: str or void*)みたいなしっかりしたものがあってもいいかもとは思いました．使われるかどうかはわかりませんが，例えばモデルファイルでパースされなかったkey-valueをその辞書にいれるとかできると使う人もいるかもと思いました．

**Comment by zhidao** [comment]
削除しました（少し前から#if 0で無効化していました）。
追加情報の辞書は面白いアイデアですね。モデルファイルについては、各種データ作成のために何度も読み直して、現在の処理に関係あるタグだけ拾っていく（関係ないものはコメントとして扱う）という実装にしているので、直接採用は難しい気がしますが、需要が出てきたら考えます。
