### ISSUE TITLE
Implementation of rkChainInertiaMat.

### ISSUE THREAD

**Issue by zhidao** [mi-lib/roki#19]
@categoryik As you know, rkChainInertiaMat() doesn't work correctly if some external forces are applied to links. I'd like to modify it to the original implementation where the bias vector is cancelled, i.e., $$h_i=\tau(q,\dot{q},e_i)-\tau(q,\dot{q},0).$$
Do you agree?

**Comment by categoryik** [comment]
No, problem.

**Comment by zhidao** [comment]
Done.
