### ISSUE TITLE
rkJointClone does not copy Joint properties

### ISSUE THREAD

**Issue by n-wakisaka** [mi-lib/roki#26]
In the `rkJointClone` function, it seems that the properties of the Joint are not being copied.
Ideally, I believe the properties output by `rkJointFPrintZTK` should be copied.

**Comment by zhidao** [comment]
I also modified specification of rkJoint largely. Please refer #27 and check if my revision doesn't have any problem.

**Comment by zhidao** [comment]
@n-wakisaka 
Is it OK to close this issue?

**Comment by n-wakisaka** [comment]
@zhidao 
It's fine to close this issue. Thank you!
