### ISSUE TITLE
Abstracting rkIK Constraint

### ISSUE THREAD

**Issue by kdaic** [mi-lib/roki#35]
In rkIK, I would like the types that uniquely represent the following items to be stored when registration so that they can be read later.

- target : COM/LINK, 
- quantity : POSITION/ATTITUDE/ANGULAR MOMENT
- reference frame : WOLRD/SUB_LINK

And, I would like it to be defined as a system value, and users can add any type as long as it does not overlap.
Please see below for usage assumptions. 
https://github.com/mi-lib/roki/pull/29

**Comment by zhidao** [comment]
`rkIKConstraint` class has been added to abstract the IK constraints. Accompanying with this, a member `mask` of `rkIKAttr` has been added to store validated attributes. I also moved a member `mode` of `rkIKAttr` to `rkIKCell`, though this is not related with the above issues. While I'm still implementing additional functions to output the IK configuration to a file now, I'd like to deal with an extension of the prioritized inverse kinematics in advance. https://github.com/mi-lib/roki/issues/30#issue-2228070467

**Comment by zhidao** [comment]
I've implemented the hierarchical prioritized inverse kinematics https://github.com/mi-lib/roki/issues/30#issuecomment-2238973006 and also `rkChainIKConfFPrintZTK()` and `rkChainIKConfWriteZTK()`. I'll close this issue if you don't have any concern about this.

**Comment by zhidao** [comment]
Let me close this issue.
